"""Add password reset token fields to Student model

Revision ID: 50d047bc5aca
Revises: 
Create Date: 2025-08-04 19:25:18.131650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d047bc5aca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiration')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
